config/routes.rb
Rails.application.routes.draw do

  resource :session, only: [:new, :create, :destroy]

  resources :users
   
  resources :events, only: [:create, :new, :show] do
    resource :venues, only: [:create, :new]
    resource :guests, only: [:create, :new]
    get "/confirmation", to: "events#confirmation", as: "confirmation" 
    get "/details", to: "events#details", as: "details" 
  end

  root to: 'events#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user
  has_many :invitations
  has_many :guests, through: :invitations
end

app/models/guest.rb
class Guest < ActiveRecord::Base
  has_many :invitations
  has_many :events, through: :invitations
end

app/models/invitation.rb
class Invitation < ActiveRecord::Base
  belongs_to :guest
  belongs_to :event
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :events

  has_secure_password

  validates :email, presence: true, uniqueness: true
  validates :name, presence: true
  validates :password, length: { in: 1..20}, on: :create
end

app/models/venue.rb
class Venue < ActiveRecord::Base
  belongs_to :event
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :event
  belongs_to :guest
  belongs_to :venue
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  # def authenticate
  #   authenticate_or_request_with_http_digest do |username| USER[username]
  #   end
  # end


end

app/controllers/events_controller.rb
require 'pry'

class EventsController < ApplicationController

  def index
    render :index
  end


  def create

    hour = params[:hour].to_i
    minutes = params[:minutes].to_i

    if params[:am_pm] == '12'
      hour += 12
    end

    year = Time.now.year
    month = Time.now.month
    day = Time.now.day

    time = "#{year}-#{month}-#{day} #{hour}:#{minutes}:#00 +0000".to_datetime

    title = params[:event][:title]
    @event = Event.new(title: title, time: time, user_id: current_user.id)
    if @event.save
      redirect_to new_event_venues_path(event_id: @event.id)
    else
      render :new
    end
  end

  def show
    render :show
  end

  def new
    @event = Event.new
  end

  def confirmation
    render :confirmation
  end

  def details
    @event = Event.where(id: params[:event_id]).first
    render :details
  end  

end

app/controllers/guests_controller.rb
require 'pry'

class GuestsController < ApplicationController


  def create
    name = params[:guest][:name]
    phone = params[:guest][:phone]

    @guest = Guest.new(
      name: name, 
      phone: phone
      )
    if @guest.save
      @guest.invitations.create(event_id: params[:event_id])
      redirect_to event_confirmation_path(event_id: params[:event_id])
    else
      render :new
    end
  end

  def new
    @guest = Guest.new
  end


  protected

  def venue_params
    params.require(:guest).permit(:event_id) # y no name?
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController


  def new
  end

  def create
    user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash.now[:alert] = "Log in failed :("
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Tsuus!"
  end
end

app/controllers/texts_controller.rb
class TextsController < ApplicationController
  def create
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Welcome aboard, #{@user.name}!"
    else
      render :new
    end
  end

  def new
    @user = User.new
  end

  def edit
  end

  def show
  end

  def update
  end

  def destroy
  end


  protected

  def user_params
    params.require(:user).permit(:name, :email, :phone, :password)
    
  end
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController


  def create
    name = params[:venue][:name]
    @venue = Venue.new(event_id: params[:event_id], name: name)
    if @venue.save
      redirect_to new_event_guests_path(event_id: @venue.event_id)
    else
      render :new
    end
  end

  def new
    @venue = Venue.new
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/confirmation_helper.rb
module ConfirmationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/texts_helper.rb
module TextsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/events/confirmation.html.erb
confirmation page!

<%= link_to "See Details", event_details_path %>

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/details.html.erb
deets.
<br>
Guests:
<% @event.guests.each do |guest| %>
  <li><%= guest.name %>
<% end %>

<br>
Venues:
<% @event.venues.each do |venue| %>
  <li><%= venue.name %>
<% end %>

app/views/events/index.html.erb
<div>
  <li role="presentation"><a href="/">Home</a></li>
  <li role="presentation"><a href="/events/new">Make Event</a></li>
  <li role="presentation"><a href="/events/<%= session[:event_id] %>">Event Status</a></li>
    </ul>
  </nav>
  <a href="/"><img src="/images/rallytally.png" width="20%" height="20%"></a>
  <br>
</div>


<!-- Hardcoded Nav-Bar above -->

<div>
  <center>
    <img src="images/rallytally_title.png" height="70%" width="70%">
       <p><h2>For when you just don't have the<br>patience to tally up them rally's votes.</h2><br></p>
    <br>
    <p>
      <%= link_to "Start Inviting!", new_event_path %>
    </p>



      <p><a class="btn btn-lg btn-success" href="/user/event/new" role="button">Start Inviting!</a></p>
  </center>
</div>

app/views/events/new.html.erb
<%= form_for @event, url: {action: 'create'} do |f| %>

<div>
  <%= f.label "title" %><br>
  <%= f.text_field :title %>
</div>

<div>
  <%= select_tag :hour, options_for_select(
    [
      ['hour'],
      ['1',1],
      ['2',2],
      ['3',3],
      ['4',4],
      ['5',5],
      ['6',6],
      ['7',7],
      ['8',8],
      ['9',9],
      ['10',10],
      ['11',11],
      ['12',12],
    ]
      ) %>
    <%= select_tag :minutes, options_for_select(
    [
      ['minute'],
      ['00',00],
      ['15',15],
      ['30',30],
      ['45',45]
    ]
      ) %>
    <%= select_tag :am_pm, options_for_select(
    [
      ['pm',12],
      ['am',0]
    ]
      ) %>


<%= f.submit "Submit" %>
<% end %>




<form class method="post" action="/events/create">
 <!--method="POST" action="/login"-->
  <div>
    <div><br><h1>STEP 1:<br><h2>Event Name & Time</h2></h1><br></div><br>
    <label for="name" class="sr-only">Event Name</label>
    <input type="text" name="title" value="" class="form-control" autocomplete="off" placeholder="Event Name... e.g. Party at Emily's!" require autofocus>
    <br>
    <!-- <h2>Event Time</h2> -->

    <div>
       <select name="hour" class="btn btn-warning dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
          <option>Hour</option>
          <option name="hour" value="1">1</option>
          <option name="hour" value="2">2</option>
          <option name="hour" value="3">3</option>
          <option name="hour" value="4">4</option>
          <option name="hour" value="5">5</option>
          <option name="hour" value="6">6</option>
          <option name="hour" value="7">7</option>
          <option name="hour" value="8">8</option>
          <option name="hour" value="9">9</option>
          <option name="hour" value="10">10</option>
          <option name="hour" value="11">11</option>
          <option name="hour" value="12">12</option>
       </select>
       <select name="minutes" class="btn btn-warning dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
          <option>Minutes</option>
          <option name="minutes" value="0">00</option>
          <option name="minutes" value="15">15</option>
          <option name="minutes" value="30">30</option>
          <option name="minutes" value="45">45</option>
       </select>
       <select name="am_pm" class="btn btn-warning dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
          <option name="am_pm" value="0">AM</option>
          <option name="am_pm" value="12">PM</option>
       </select>  
       <input class="btn btn-lg btn-success" type="submit" value="Continue">
    </div>
  
<!--     <a class="btn btn-lg btn-primary btn-block" href="/events/[:event_id]/venues"> Continue </a> -->
  </div>
</form>

app/views/events/show.html.erb
<h1>Events#show</h1>
<p>Find me in app/views/events/show.html.erb</p>

app/views/events/venues.html.erb
 <%= form_for @venue, url: {action: 'create'} do |f| %>

<div>
  <%= f.label "name" %><br>
  <%= f.text_field :name %>
</div>

<%= f.submit "Submit" %>
<% end %>






 <div>
    <div><br><h1>STEP 2:<br><h2>Venue Choices</h2></h1><br></div><br>

    <% if @venues != nil %>
    <% @venues.each do |venue| %>
      <div class="venuebox">
      <ul class="indent_if_newline"><li><%= venue.name %></li></ul>
      </div>
    <% end %>
  <% end %>

    <form class="form-signin" method="post" action="/events/venues">
      <input type="text" name="name" value="" class="form-control" autocomplete="off" placeholder="Venue..." required autofocus>
      <br>

      <input type="hidden" name="event_id" value=<%= @event.id %>>
      <input class="btn btn-lg btn-warning" type="submit" value="Add Venue">
      <% if @venues.count > 0 %> 
        <a class="btn btn-lg btn-success" href="/events/<%= @event.id %>/guests"> Continue</a>
      <% end %>

    </form>
  </div>

app/views/guests/new.html.erb
 <%= form_for @guest, url: {action: 'create'} do |f| %>

<div>
  <%= f.label "name" %><br>
  <%= f.text_field :name %>
</div>
<div>
  <%= f.label "phone" %><br>
  <%= f.text_field :phone %>
</div>


<%= f.submit "Submit" %>
<% end %>






  

app/views/texts/create.html.erb
<h1>Texts#create</h1>
<p>Find me in app/views/texts/create.html.erb</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/new.html.erb
<h1>Sign Up</h1>


<%= form_for @user do |f| %>

<div>
  <%= f.label "name" %> <br>
  <%= f.text_field "name" %>
</div>

<div>
  <%= f.label "email" %> <br>
  <%= f.text_field "email" %>
</div>

<div>
  <%= f.label "phone" %> <br>
  <%= f.text_field "phone" %>
</div>

<div>
  <%= f.label "password" %> <br>
  <%= f.password_field "password" %>
</div>

<div>
  <%= f.submit "Submit"%>
</div>

<% end %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>

app/views/venues/new.html.erb
 <%= form_for @venue, url: {action: 'create'} do |f| %>

<div>
  <%= f.label "name" %><br>
  <%= f.text_field "name" %>
</div>

<%= f.submit "Submit" %>
<% end %>






 